### ISSUE TITLE
Login required error for the classic universal login

### ISSUE THREAD

**Issue by eluzhnica** [conradbez/streamlit-auth0#1]
Thanks a lot for this much needed component!

The component works flawlessly if you make a Single Page Application with the "New" universal login. However, the "New" universal login (Branding > Universal Login > New) has problems with SSO as noted here https://community.auth0.com/t/no-connections-enabled-for-the-client-but-saml-connection-is-enabled/62759. 

If you use the "Classical" universal login the component starts breaking with `Login required` (some context on when that happens on auth0 here https://community.auth0.com/t/failed-silent-auth-login-required/33165/38).

To reproduce it all you need to do is go to Branding > Universal Login and select Classical. The same app breaks. 

Any ideas on how to go around it? Plans on supporting it?

**Comment by conradbez** [comment]
Hi @eluzhnica thanks so much for the praises. 

No plans at the moment, what’s the error code and stack trace (or behaviour) it gives you when it brakes?

Also if you could open your “console” output in the browser (under settings / Developer) and post the error message I can have a look at it.

**Comment by eluzhnica** [comment]
@conradbez Yes, here's the error shown on cosole:

```
Uncaught (in promise) Error: Login required
    at new e (errors.tsx:9)
    at utils.tsx:15
    at auth0-provider.tsx:306
    at 2.4ac5b17e.chunk.js:2
    at Object.throw (2.4ac5b17e.chunk.js:2)
    at u (2.4ac5b17e.chunk.js:2)
 ```
 
 The streamlit app gives no error, so nothing to show there.
 
 Auth0 has nothing relevant on the logs except type: `Failed Silent Auth` and description: `Login required`.

**Comment by conradbez** [comment]
Thanks, I suspect this might have something to
Do with the usage of “*getAccessTokenSilently” being blocked by your
browser. 

Can you try a different browser and maybe replace getAccessTokenSilently
with getAccessTokenWithPopup if you know how to do that.

**Comment by eluzhnica** [comment]
> Can you try a different browser

I've tried with Safari, Chrome, Firefox, same issue. Tried incognito mode too.


> with getAccessTokenWithPopup if you know how to do that.

That works, yes! Although at the expense that now the user is triggered twice everytime.

**Comment by conradbez** [comment]
Nice nice!

okay I think to fix it (and this is something I wanted to do before) we’ll need to 
(1) change that component to a class 
(2) give that class a state variable “authToken” = false
(3) before we fetch a new auth token we 
   - check if (! authToken ) and skip if we have a token
   - try silentAuthToken 
   - Try popupAuthToken
   - setState({authToken:recieved_auth_token})
  
 Don't have time atm but might try something over the weekend. Happy to PR if you get it working. 

(Sorry for bad formatting I'm on my phone)
