### ISSUE TITLE
Any way to make the component keep its state when used in multi page streamlit app?

### ISSUE THREAD

**Issue by tp-rbrasset** [conradbez/streamlit-auth0#12]
I have a simple streamlit app with 2 pages (A and B) and used the login_button component in either pages. When the login is done in the A page the component shows the logout text and allows the user to logout the session.

However when the user changes to page B, the login_button instantiated in that page doesn't maintain the logged in state, and another message to login is shown.

PS: I have instantiated the login button using the key optional parameter as "login" in both pages.

Is there any way to keep the component state even if the user changed page after the login?

I am available to help with development if necessary. Although I'm not an experienced programmer, I'm willing to help,

**Comment by conradbez** [comment]
I think you could possibly do this on your end with user session state

You'd check the user session state store for credentials and only if they're not there would you use the login button

After successful login you store the creds in the store

Not something I'm looking to build into this library though
