### ISSUE TITLE
Send user's metadata

### ISSUE THREAD

**Issue by raimundovidal13** [conradbez/streamlit-auth0#14]
This works great for use cases in which you have the same level of permission for all users, but if for instance you want to have different roles per user which entitles different functionalities, just grabbing the user basic info might require additional work, could you also get the user's metadata? that way you can set-up the custom attributes for your users and get it directly just using this library

**Comment by conradbez** [comment]
Great idea! Not in what I have time for atm but happy to take a PR!

**Comment by mullenba** [comment]
@raimundovidal13 You can do it through Auth0 itself.

https://auth0.com/docs/get-started/apis/scopes/sample-use-cases-scopes-and-claims#add-custom-claims-to-a-token
