### ISSUE TITLE
Remove domain check?

### ISSUE THREAD

**Issue by jolmes** [conradbez/streamlit-auth0#20]
Would you remove the domain check on line 26 of __init__.py? It would allow us to work with Auth0 from different regions. My auth0 domain is just .auth0.com

**Comment by jrvidotti** [comment]
Same issue here, too!

**Comment by jlschattschneider** [comment]
Same here!

**Comment by fonnebien** [comment]
@jolmes @vidz1979 @jlschattschneider Issue is handled in #21

**Comment by conradbez** [comment]
https://github.com/conradbez/streamlit-auth0/pull/17
