### ISSUE TITLE
Can't load auth0_component.login_button in prod

### ISSUE THREAD

**Issue by matt-bornstein** [conradbez/streamlit-auth0#24]
I can run this component in dev - works great!

But deploying to prod (on fly.io), I get this error ("Your app is having trouble loading the auth0_component.login_button component.")

The frontend code is correctly copied to the server, and I'm able to import the python module. Maybe it's a network issue? Does a new port need to be forwarded for a separate process serving the html/ javascript?

Any ideas? Thank you!!

<img width="744" alt="image" src="https://github.com/conradbez/streamlit-auth0/assets/26883865/385f4fdf-baf0-4031-b72f-58234631a32f">

**Comment by conradbez** [comment]
Okay, should have been fixed with previous update - let me know if this issue persists
