### ISSUE TITLE
How to allow other domains than just .us

### ISSUE THREAD

**Issue by candia-julian** [conradbez/streamlit-auth0#25]
Just delete the following line of code or modify it to allow others domains

https://github.com/conradbez/streamlit-auth0/blob/c5e5666d93b3fd29b3df7f12f5e31c50dd68892b/auth0_component/__init__.py#L26

It just worked for my. That harcoded line must be deleted or modified to handle other domains.

**Comment by peterdudfield** [comment]
me too

**Comment by fonnebien** [comment]
@candia-julian @peterdudfield This issue is handled in PR #17 , custom domains and some smaller improvements are handled in #19 .

**Comment by conradbez** [comment]
https://github.com/conradbez/streamlit-auth0/pull/17
