### ISSUE TITLE
user_info returning false

### ISSUE THREAD

**Issue by michaelfouad** [conradbez/streamlit-auth0#6]
user_info is returning a boolean, and after authentication, it does not turn true. 
running simple app in auth0

**Comment by charlielito** [comment]
Same bug here

**Comment by charlielito** [comment]
The logs are the following
![Screenshot from 2022-01-24 14-03-04](https://user-images.githubusercontent.com/8033598/150847247-071f578f-af57-46d1-a9ac-fbca399ded92.png)

**Comment by ofersabo** [comment]
Same bug here. user_info is false although it seems that authentication succeeded.
We're using auth0 URL that ends with eu. 
Do you have any assumptions regarding the auth0 URL? 

<img width="710" alt="image" src="https://user-images.githubusercontent.com/31179968/156924062-e38827f3-9831-4f62-bab8-e457ff688d65.png">

**Comment by hunkim** [comment]
@charlielito @ofersabo Did you figure it out? I do have the same bug.

**Comment by charlielito** [comment]
> @charlielito @ofersabo Did you figure it out? I do have the same bug.

Sadly no, and @conradbez seems to ignore us :(

**Comment by eluzhnica** [comment]
I believe these issues are fixed part of https://github.com/conradbez/streamlit-auth0/issues/1.  Can you try `pip install git+https://github.com/eluzhnica/streamlit-auth0.git@fix-old-universal-login-builds#egg=streamlit-auth0-component` and let me know if that works?

**Comment by charlielito** [comment]
> I believe these issues are fixed part of #1. Can you try `pip install git+https://github.com/eluzhnica/streamlit-auth0.git@fix-old-universal-login-builds#egg=streamlit-auth0-component` and let me know if that works?

Nope, same behavior

**Comment by blackary** [comment]
@charlielito Try doing `pip uninstall streamlit-auth0-component` first and then `pip install git+https://github.com/eluzhnica/streamlit-auth0.git@fix-old-universal-login-builds#egg=streamlit-auth0-component` -- that worked for me, even though just installing didn't work.

**Comment by charlielito** [comment]
> @charlielito Try doing `pip uninstall streamlit-auth0-component` first and then `pip install git+https://github.com/eluzhnica/streamlit-auth0.git@fix-old-universal-login-builds#egg=streamlit-auth0-component` -- that worked for me, even though just installing didn't work.

following your instructions it worked! thanks!

**Comment by conradbez** [comment]
I think this is implemented in the latest vanilla js [merge](https://github.com/conradbez/streamlit-auth0/pull/10) and this [commit](https://github.com/conradbez/streamlit-auth0/commit/1396a8a701979f5e26fe18c7f25c517c2c7932d4)
