### ISSUE TITLE
Inner iframe when logging out

### ISSUE THREAD

**Issue by slezakbs** [conradbez/streamlit-auth0#7]
Logging in works great,  but when I log out it creates another iframe inside my app (see demo gif attached). I think this is caused by a returnTo redirect enforced by auth0 SDK (essentially refreshing the frontend component).  Is there a way to better handle this or is this an issue?

![demo](https://user-images.githubusercontent.com/6465705/152606346-38607318-e515-4d30-aab9-767599b4e895.gif)

**Comment by conradbez** [comment]
Uhm that’s weird I’ve never had this issue.

If you’re able to find a solution please submit a PR.

**Comment by slezakbs** [comment]
Dang, that's unfortunate.  btw, this only happens when I try to import the release `from auth0_component import login_button`.  Strangely, if I run the app with `RELEASE=false` then I don't see this issue.  Anyway, I'll push PR if I figure it out

**Comment by conradbez** [comment]
I believe this is fixed now. Thanks for the code, ended up copy pasting your solution thanks :)
